package com.tech.m.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-21T09:17:10.057+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "urn:api.m-tech.com", name = "MTechAPI")
@XmlSeeAlso({com.tech.m.api.inventory.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.tech.m.api.messaging.ObjectFactory.class, com.tech.m.api.issue.ObjectFactory.class, com.tech.m.api.serviceorder.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class, com.tech.m.api.fault.ObjectFactory.class, com.tech.m.api.guest.ObjectFactory.class, com.tech.m.api.room.ObjectFactory.class, org.datacontract.schemas._2004._07.messaging.ObjectFactory.class})
public interface MTechAPI {

    @WebMethod(action = "urn:api.m-tech.com/send")
    @Action(input = "urn:api.m-tech.com/send", output = "urn:api.m-tech.com/sendResponse", fault = {@FaultAction(className = MTechAPISendApiFaultFaultMessage.class, value = "urn:api.m-tech.com/sendFault")})
    @RequestWrapper(localName = "send", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.SendResponse")
    @WebResult(name = "sendResult", targetNamespace = "urn:api.m-tech.com")
    public com.tech.m.api.ApiObject send(
        @WebParam(name = "apiObject", targetNamespace = "urn:api.m-tech.com")
        com.tech.m.api.ApiObject apiObject
    ) throws MTechAPISendApiFaultFaultMessage;

    @WebMethod(action = "urn:api.m-tech.com/delete")
    @Action(input = "urn:api.m-tech.com/delete", output = "urn:api.m-tech.com/deleteResponse", fault = {@FaultAction(className = MTechAPIDeleteApiFaultFaultMessage.class, value = "urn:api.m-tech.com/deleteFault")})
    @RequestWrapper(localName = "delete", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.DeleteResponse")
    @WebResult(name = "deleteResult", targetNamespace = "urn:api.m-tech.com")
    public com.tech.m.api.ApiObject delete(
        @WebParam(name = "apiObject", targetNamespace = "urn:api.m-tech.com")
        com.tech.m.api.ApiObject apiObject
    ) throws MTechAPIDeleteApiFaultFaultMessage;

    @WebMethod(action = "urn:api.m-tech.com/get")
    @Action(input = "urn:api.m-tech.com/get", output = "urn:api.m-tech.com/getResponse", fault = {@FaultAction(className = MTechAPIGetApiFaultFaultMessage.class, value = "urn:api.m-tech.com/getFault")})
    @RequestWrapper(localName = "get", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "urn:api.m-tech.com", className = "com.tech.m.api.GetResponse")
    @WebResult(name = "getResult", targetNamespace = "urn:api.m-tech.com")
    public com.tech.m.api.ApiObject get(
        @WebParam(name = "apiObject", targetNamespace = "urn:api.m-tech.com")
        com.tech.m.api.ApiObject apiObject
    ) throws MTechAPIGetApiFaultFaultMessage;
}
