package com.tech.m.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-21T09:17:10.073+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "MTechAPI", 
                  wsdlLocation = "file:soap.xml",
                  targetNamespace = "urn:api.m-tech.com") 
public class MTechAPI_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:api.m-tech.com", "MTechAPI");
    public final static QName SOAP = new QName("urn:api.m-tech.com", "SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:soap.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MTechAPI_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:soap.xml");
        }
        WSDL_LOCATION = url;
    }

    public MTechAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MTechAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTechAPI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MTechAPI_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MTechAPI_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MTechAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MTechAPI
     */
    @WebEndpoint(name = "SOAP")
    public MTechAPI getSOAP() {
        return super.getPort(SOAP, MTechAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTechAPI
     */
    @WebEndpoint(name = "SOAP")
    public MTechAPI getSOAP(WebServiceFeature... features) {
        return super.getPort(SOAP, MTechAPI.class, features);
    }

}
